// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace RefundProcessor
{
    public partial class RefundDecisionModel
    {
        /// <summary>
        /// model input class for RefundDecisionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Category")]
            public string Category { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"DaysSincePurchase")]
            public float DaysSincePurchase { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"PriorRefundCount")]
            public float PriorRefundCount { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"CustomerTenureDays")]
            public float CustomerTenureDays { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"ReasonCode")]
            public string ReasonCode { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"IsInternationalOrder")]
            public bool IsInternationalOrder { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"ShippingCountryMismatch")]
            public bool ShippingCountryMismatch { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"IsHighRiskPayment")]
            public bool IsHighRiskPayment { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"RequiresApproval")]
            public bool RequiresApproval { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for RefundDecisionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Category")]
            public float[] Category { get; set; }

            [ColumnName(@"DaysSincePurchase")]
            public float DaysSincePurchase { get; set; }

            [ColumnName(@"PriorRefundCount")]
            public float PriorRefundCount { get; set; }

            [ColumnName(@"CustomerTenureDays")]
            public float CustomerTenureDays { get; set; }

            [ColumnName(@"ReasonCode")]
            public float[] ReasonCode { get; set; }

            [ColumnName(@"IsInternationalOrder")]
            public float[] IsInternationalOrder { get; set; }

            [ColumnName(@"ShippingCountryMismatch")]
            public float[] ShippingCountryMismatch { get; set; }

            [ColumnName(@"IsHighRiskPayment")]
            public float[] IsHighRiskPayment { get; set; }

            [ColumnName(@"RequiresApproval")]
            public bool RequiresApproval { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("RefundDecisionModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
