// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Sentence_similarity
{
    public partial class SentenceSimilarity
    {
        /// <summary>
        /// model input class for SentenceSimilarity.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(3)]
            [ColumnName(@"search_term")]
            public string Search_term { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"relevance")]
            public float Relevance { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"product_description")]
            public string Product_description { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentenceSimilarity.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"search_term")]
            public string Search_term { get; set; }

            [ColumnName(@"relevance")]
            public float Relevance { get; set; }

            [ColumnName(@"product_description")]
            public string Product_description { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentenceSimilarity.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            mlContext.GpuDeviceId = 0;
            mlContext.FallbackToCpu = false;
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
