// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TechJobsSalaries.ConsoleApp
{
    public partial class TechJobsSalaries
    {
        /// <summary>
        /// model input class for TechJobsSalaries.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"TenureInOrgInMonths")]
            public float TenureInOrgInMonths { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"GrossPay")]
            public float GrossPay { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"JobTitle")]
            public string JobTitle { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Department")]
            public string Department { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TechJobsSalaries.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"TenureInOrgInMonths")]
            public float TenureInOrgInMonths { get; set; }

            [ColumnName(@"GrossPay")]
            public float GrossPay { get; set; }

            [ColumnName(@"JobTitle")]
            public float[] JobTitle { get; set; }

            [ColumnName(@"Department")]
            public float[] Department { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TechJobsSalaries.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
